[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs
'''

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "B", "I", "N", "UP", "S", "BLE", "FBT", "C4", "DTZ", "T10", "EM", "ISC"]
ignore = [
    "S108",    # Temp directory usage
    "BLE001",  # Blind except
    "EM102",   # F-string in exception
    "EM101",   # String literals in exceptions
    "DTZ005",  # Timezone-naive datetime
    "B904",    # Raise from err
    "B905",    # Zip without strict
]

[tool.ruff.per-file-ignores]
"backup.py" = ["E501"]  # Line too long

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
    "B101",  # assert statements
    "B108",  # hardcoded tmp directory
    "B601",  # paramiko command injection (we trust the input)
]

[tool.pylint]
max-line-length = 100
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0330",  # bad-continuation
    "C0326",  # bad-whitespace
]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
