[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "B", "I", "N", "UP", "S", "BLE", "FBT", "C4", "DTZ", "T10", "EM", "ISC"]
ignore = []

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]

[tool.pylint]
max-line-length = 100
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0330",  # bad-continuation
    "C0326",  # bad-whitespace
] 