apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.fullname" . }}-config
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |
    [logging]
    level = "{{ .Values.logging.level }}"

    [ssh]
    {{- if .Values.ssh.existingSecret }}
    username = "${MIKROTIK_SSH_USER}"
    {{- else }}
    username = "{{ .Values.ssh.username }}"
    {{- end }}
    key_path = "{{ .Values.ssh.keyPath }}"

    [backup]
    local_dir = "{{ .Values.backup.localDir }}"
    format = "{{ .Values.backup.format }}"

    [storage]
    {{- if .Values.storage.existingSecret }}
    type = "${MIKROTIK_S3_TYPE}"
    bucket = "${MIKROTIK_S3_BUCKET}"
    endpoint = "${MIKROTIK_S3_ENDPOINT}"
    access_key = "${MIKROTIK_S3_ACCESS_KEY}"
    secret_key = "${MIKROTIK_S3_SECRET_KEY}"
    {{- else }}
    type = "{{ .Values.storage.type }}"
    bucket = "{{ .Values.storage.bucket }}"
    endpoint = "{{ .Values.storage.endpoint }}"
    access_key = "{{ .Values.storage.s3Credentials.accessKey }}"
    secret_key = "{{ .Values.storage.s3Credentials.secretKey }}"
    {{- end }}

    [retention]
    daily = {{ .Values.retention.daily }}
    monthly = {{ .Values.retention.monthly }}
    yearly = {{ .Values.retention.yearly }}

    [devices]
    routers = [
      {{- range .Values.devices.routers }}
      "{{ . }}",
      {{- end }}
    ]
