apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.fullname" . }}-config
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |
    [ssh]
    {{- if not .Values.ssh.existingSecret }}
    username = "{{ .Values.ssh.username }}"
    key_path = "{{ .Values.ssh.keyPath }}"
    {{- end }}

    [backup]
    local_dir = "{{ .Values.backup.localDir }}"
    format = "{{ .Values.backup.format }}"

    [storage]
    type = "{{ .Values.storage.type }}"
    {{- if not .Values.storage.credentials.existingSecret }}
    bucket = "{{ .Values.storage.bucket }}"
    endpoint = "{{ .Values.storage.endpoint }}"
    access_key = "{{ .Values.storage.credentials.accessKey }}"
    secret_key = "{{ .Values.storage.credentials.secretKey }}"
    {{- end }}

    [retention]
    daily = {{ .Values.retention.daily }}
    monthly = {{ .Values.retention.monthly }}
    yearly = {{ .Values.retention.yearly }}

    [devices]
    routers = [
      {{- range .Values.devices.routers }}
      "{{ . }}",
      {{- end }} 
    ]
