{{- if eq .Values.deploymentMode "daemon" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mikrotik-backup.fullname" . }}
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mikrotik-backup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mikrotik-backup.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mikrotik-backup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args:
            - "/app/backup.py"
            - "--mode"
            - "daemon"
            - "--times"
            {{- range .Values.backup.times }}
            - "{{ . }}"
            {{- end }}
            - "--jobs"
            - "{{ .Values.backup.jobs }}"
            - "--key"
            - "{{ .Values.ssh.keyPath }}"
            {{- if .Values.backup.executeOnStart }}
            - "--onstart"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/mikrotik_backup.toml
              subPath: config.toml
            - name: ssh-key
              mountPath: {{ .Values.ssh.keyPath }}
              subPath: ssh-key
          env:
            - name: TZ
              value: {{ .Values.timezone }}
            {{- if .Values.storage.existingSecret }}
            - name: MIKROTIK_S3_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret }}
                  key: s3-type
            - name: MIKROTIK_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret }}
                  key: s3-bucket
            - name: MIKROTIK_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret }}
                  key: s3-endpoint
            - name: MIKROTIK_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret }}
                  key: access-key
            - name: MIKROTIK_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret }}
                  key: secret-key
            {{- end }}
            {{- if .Values.ssh.existingSecret }}
            - name: MIKROTIK_SSH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ssh.existingSecret }}
                  key: username
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "mikrotik-backup.fullname" . }}-config
        - name: ssh-key
          secret:
            secretName: {{ include "mikrotik-backup.sshSecretName" . }}
            defaultMode: 0600
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
