{{- if not .Values.storage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.fullname" . }}-credentials
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3-type: "{{ .Values.storage.type }}"
  s3-bucket: "{{ .Values.storage.bucket }}"
  s3-endpoint: "{{ .Values.storage.endpoint }}"
  access-key: "{{ .Values.storage.s3Credentials.accessKey }}"
  secret-key: "{{ .Values.storage.s3Credentials.secretKey }}"
{{- end }}

{{- if and (not .Values.ssh.existingSecret) .Values.ssh.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.sshSecretName" . }}
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.ssh.username }}"
  ssh-key: |
{{ .Values.ssh.key | indent 4 }}
{{- end }}
