{{- if not .Values.storage.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.fullname" . }}-credentials
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.storage.credentials.accessKeyKey }}: {{ .Values.storage.credentials.accessKey | b64enc }}
  {{ .Values.storage.credentials.secretKeyKey }}: {{ .Values.storage.credentials.secretKey | b64enc }}
{{- end }}

{{- if and (not .Values.ssh.existingSecret) .Values.ssh.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-backup.sshSecretName" . }}
  labels:
    {{- include "mikrotik-backup.labels" . | nindent 4 }}
type: Opaque
stringData:  # Use stringData for raw key
  {{ .Values.ssh.secretKey }}: {{ .Values.ssh.key }}
{{- end }} 