# Application-specific configuration
deploymentMode: "cronjob" # "daemon" or "cronjob"

# Logging configuration
logging:
  level: "info"  # Possible values: debug, info, warning, error

# Backup configuration
backup:
  times: ["02:00", "10:00", "18:00"]
  jobs: 4
  format: "plain"  # or "json"
  localDir: "/tmp/mikrotik_backups"
  executeOnStart: true  # Execute a backup when the daemon starts

# SSH configuration
ssh:
  username: "backupper"
  keyPath: "/mikrotik-rsa"
  existingSecret: ""  # Name of existing secret containing SSH credentials
  key: ""  # SSH private key (used if existingSecret is empty)

# Storage configuration (S3-compatible)
storage:
  type: ""      # wasabi, s3, etc
  bucket: ""    # bucket name
  endpoint: ""  # endpoint URL
  existingSecret: ""  # Name of existing secret containing S3 credentials
  s3Credentials:
    accessKey: "" # access key
    secretKey: "" # secret key

# Device configuration
devices:
  routers: []  # List of router IPs

# Retention configuration
retention:
  daily: 30
  monthly: 12
  yearly: 5

# Timezone configuration
timezone: "Europe/Rome"

# Generic Kubernetes configuration
image:
  repository: ghcr.io/thekoma/mikrotik-backup/app
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
