name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        if: success()
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        if: success()
        run: |
          python -m pip install --upgrade pip
          pip install boto3 paramiko colorama tomli schedule

      - name: Generate version
        if: success()
        id: generate-version
        run: |
          # Get current date and format it as YYYY.MM
          CURRENT_DATE=$(date +%Y.%m)
          # Get latest tag and extract release number
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo "v0.0.0")
          LATEST_RELEASE_NUMBER=$(echo "$LATEST_TAG" | cut -d '.' -f 3 | cut -d 'v' -f 2)
          # Increment release number if same month, otherwise reset to 0
          if [[ "$(date +%Y.%m)" == "$(echo "$LATEST_TAG" | cut -d '.' -f 1,2 | cut -d 'v' -f 2)" ]]; then
            RELEASE_NUMBER=$((LATEST_RELEASE_NUMBER + 1))
          else
            RELEASE_NUMBER=0
          fi
          # Set VERSION environment variable
          VERSION="v$CURRENT_DATE.$RELEASE_NUMBER"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          # Update Chart.yaml with new version
          sed -i "s/^version:.*$/version: ${VERSION#v}/" charts/mikrotik-backup/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${VERSION#v}\"/" charts/mikrotik-backup/Chart.yaml

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        if: success()
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/thekoma/mikrotik-backup/app
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: Build and push multi-arch Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Login to GitHub Container Registry (Helm)
        if: success()
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Chart | Push
        if: success()
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: mikrotik-backup
          repository: thekoma/mikrotik-backup/charts
          tag: ${{ env.VERSION }}
          app_version: ${{ env.VERSION }}
          path: charts/mikrotik-backup
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'

      - name: Update Version References
        if: success()
        run: |
          # Remove 'v' prefix for version number
          VERSION_WITHOUT_V="${VERSION#v}"
          
          # Update README.md
          sed -i "s/\(image: ghcr\.io\/thekoma\/mikrotik-backup\/app:\)[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\+/\1${VERSION_WITHOUT_V}/g" README.md
          sed -i "s/\(version \)[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\+/\1${VERSION_WITHOUT_V}/g" README.md
          
          # Update docker-compose.yml
          sed -i "s/\(image: ghcr\.io\/thekoma\/mikrotik-backup\/app:\)[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\+/\1${VERSION_WITHOUT_V}/g" docker-compose.yml

      - name: Commit Version Updates
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md docker-compose.yml
          git commit -m "docs: update version references to ${{ env.VERSION }}" || echo "No changes to commit"
          git push

      - name: Generate Release Notes
        if: success()
        run: |
          # Remove 'v' prefix for version number
          VERSION_WITHOUT_V="${VERSION#v}"
          cat << EOF > release_notes.md
          ## 🚀 Release ${{ env.VERSION }}

          ### 📦 Container Images
          The following multi-architecture container images are available:
          - \`ghcr.io/thekoma/mikrotik-backup/app:${VERSION_WITHOUT_V}\` (recommended for production)
          - \`ghcr.io/thekoma/mikrotik-backup/app:latest\` (latest version)

          Supported architectures:
          - linux/amd64 (Intel/AMD 64-bit)
          - linux/arm64 (ARM 64-bit)

          ### 📋 Installation Examples

          #### Docker Compose
          \`\`\`yaml
          services:
            mikrotik-backup:
              image: ghcr.io/thekoma/mikrotik-backup/app:${VERSION_WITHOUT_V}
              volumes:
                - ./config.toml:/app/config.toml:ro
                - ./mikrotik-rsa:/mikrotik-rsa:ro
              environment:
                - TZ=Europe/Rome
          \`\`\`

          #### Kubernetes with Helm
          \`\`\`bash
          # Install using Helm
          helm install mikrotik-backup oci://ghcr.io/thekoma/mikrotik-backup/charts --version ${VERSION_WITHOUT_V}
          \`\`\`

          #### Systemd Service
          \`\`\`ini
          [Unit]
          Description=Mikrotik Backup Service

          [Service]
          ExecStart=/usr/local/bin/mikrotik-backup
          User=mikrotik-backup
          WorkingDirectory=/etc/mikrotik-backup

          [Install]
          WantedBy=multi-user.target
          \`\`\`

          For more detailed installation and configuration instructions, please refer to the [README](https://github.com/thekoma/mikrotik-backup#readme).
          EOF

      - name: Commit README update
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "docs: update version references to ${{ env.VERSION }}" || echo "No changes to commit"
          git push

      - name: Create Release
        if: success() && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: release_notes.md

      - name: Cleanup
        if: always()
        run: |
          rm -f release_notes.md || true