name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install boto3 paramiko colorama tomli schedule

      - name: Increment version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/thekoma/mikrotik-backup:${{ steps.tag_version.outputs.new_tag }} .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/thekoma/mikrotik-backup:${{ steps.tag_version.outputs.new_tag }}

      - name: Package Helm Chart
        run: |
          helm package charts/mikrotik-backup
          CHART_VERSION=$(helm show chart charts/mikrotik-backup-*.tgz | grep version | awk '{print $2}')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Create Helm Chart Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            mikrotik-backup-${{ env.CHART_VERSION }}.tgz